// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateLoanSchedules implements pgx.CopyFromSource.
type iteratorForCreateLoanSchedules struct {
	rows                 []CreateLoanSchedulesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLoanSchedules) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLoanSchedules) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LoanID,
		r.rows[0].Sequence,
		r.rows[0].DueDate,
		r.rows[0].Amount,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForCreateLoanSchedules) Err() error {
	return nil
}

func (q *Queries) CreateLoanSchedules(ctx context.Context, arg []CreateLoanSchedulesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"schedules"}, []string{"loan_id", "sequence", "due_date", "amount", "status"}, &iteratorForCreateLoanSchedules{rows: arg})
}
