// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastPaidWeek = `-- name: GetLastPaidWeek :one
SELECT COALESCE(MAX(week_number), 0)::BIGINT AS last_paid_week
FROM payments
WHERE loan_id = $1
`

func (q *Queries) GetLastPaidWeek(ctx context.Context, loanID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLastPaidWeek, loanID)
	var last_paid_week int64
	err := row.Scan(&last_paid_week)
	return last_paid_week, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, principal_amount, total_interest_amount, total_payable_amount, weekly_payment_amount, total_weeks, start_date, created_at
FROM loans
WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int64) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.PrincipalAmount,
		&i.TotalInterestAmount,
		&i.TotalPayableAmount,
		&i.WeeklyPaymentAmount,
		&i.TotalWeeks,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalPaidAmount = `-- name: GetTotalPaidAmount :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total_paid
FROM payments
WHERE loan_id = $1
`

func (q *Queries) GetTotalPaidAmount(ctx context.Context, loanID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPaidAmount, loanID)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}

const insertRepayment = `-- name: InsertRepayment :one
INSERT INTO payments (loan_id, week_number, amount, paid_at)
VALUES ($1, $2, $3, $4)
RETURNING id, loan_id, week_number, amount, paid_at, created_at
`

type InsertRepaymentParams struct {
	LoanID     int64
	WeekNumber int32
	Amount     int64
	PaidAt     pgtype.Timestamp
}

func (q *Queries) InsertRepayment(ctx context.Context, arg InsertRepaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertRepayment,
		arg.LoanID,
		arg.WeekNumber,
		arg.Amount,
		arg.PaidAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.WeekNumber,
		&i.Amount,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
