// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, principal_amount, total_interest_amount, total_payable_amount, weekly_payment_amount, total_weeks, start_date, created_at
FROM loans
WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int64) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.PrincipalAmount,
		&i.TotalInterestAmount,
		&i.TotalPayableAmount,
		&i.WeeklyPaymentAmount,
		&i.TotalWeeks,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertLoan = `-- name: InsertLoan :one
INSERT INTO loans (
    principal_amount,
    total_interest_amount,
    total_payable_amount,
    weekly_payment_amount,
    total_weeks,
    start_date
  )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, principal_amount, total_interest_amount, total_payable_amount, weekly_payment_amount, total_weeks, start_date, created_at
`

type InsertLoanParams struct {
	PrincipalAmount     int64
	TotalInterestAmount int64
	TotalPayableAmount  int64
	WeeklyPaymentAmount int64
	TotalWeeks          int32
	StartDate           pgtype.Date
}

func (q *Queries) InsertLoan(ctx context.Context, arg InsertLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, insertLoan,
		arg.PrincipalAmount,
		arg.TotalInterestAmount,
		arg.TotalPayableAmount,
		arg.WeeklyPaymentAmount,
		arg.TotalWeeks,
		arg.StartDate,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.PrincipalAmount,
		&i.TotalInterestAmount,
		&i.TotalPayableAmount,
		&i.WeeklyPaymentAmount,
		&i.TotalWeeks,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}
