// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Loan struct {
	ID                  int64
	PrincipalAmount     int64
	TotalInterestAmount int64
	TotalPayableAmount  int64
	WeeklyPaymentAmount int64
	TotalWeeks          int32
	StartDate           pgtype.Date
	CreatedAt           pgtype.Timestamp
}

type Payment struct {
	ID         int64
	LoanID     int64
	WeekNumber int32
	Amount     int64
	PaidAt     pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}
