// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPaymentsByLoanID = `-- name: ListPaymentsByLoanID :many
SELECT id,
  loan_id,
  week_number,
  amount,
  paid_at
FROM payments
WHERE loan_id = $1::bigint
  AND (
    (
      $2::timestamptz IS NULL
      AND $3::bigint IS NULL
    )
    OR (
      (paid_at, id) > (
        $2::timestamptz,
        $3::bigint
      )
    )
  )
ORDER BY paid_at ASC,
  id ASC
LIMIT $4::int
`

type ListPaymentsByLoanIDParams struct {
	LoanID       int64
	CursorPaidAt pgtype.Timestamptz
	CursorID     pgtype.Int8
	LimitVal     int32
}

type ListPaymentsByLoanIDRow struct {
	ID         int64
	LoanID     int64
	WeekNumber int32
	Amount     int64
	PaidAt     pgtype.Timestamp
}

func (q *Queries) ListPaymentsByLoanID(ctx context.Context, arg ListPaymentsByLoanIDParams) ([]ListPaymentsByLoanIDRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByLoanID,
		arg.LoanID,
		arg.CursorPaidAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsByLoanIDRow
	for rows.Next() {
		var i ListPaymentsByLoanIDRow
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.WeekNumber,
			&i.Amount,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
