// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastPaidWeek = `-- name: GetLastPaidWeek :one
SELECT COALESCE(MAX(week_number), 0)::INT AS last_paid_week
FROM payments
WHERE loan_id = $1
`

func (q *Queries) GetLastPaidWeek(ctx context.Context, loanID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getLastPaidWeek, loanID)
	var last_paid_week int32
	err := row.Scan(&last_paid_week)
	return last_paid_week, err
}

const getPaidWeeksCount = `-- name: GetPaidWeeksCount :one
SELECT COUNT(*)::INT
FROM payments
WHERE loan_id = $1
`

func (q *Queries) GetPaidWeeksCount(ctx context.Context, loanID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getPaidWeeksCount, loanID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalPaidAmount = `-- name: GetTotalPaidAmount :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total_paid
FROM payments
WHERE loan_id = $1
`

func (q *Queries) GetTotalPaidAmount(ctx context.Context, loanID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPaidAmount, loanID)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (
    loan_id,
    week_number,
    amount,
    idempotency_key,
    paid_at
  )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, loan_id, week_number, amount, idempotency_key, paid_at, created_at
`

type InsertPaymentParams struct {
	LoanID         int64
	WeekNumber     int32
	Amount         int64
	IdempotencyKey string
	PaidAt         pgtype.Timestamp
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.LoanID,
		arg.WeekNumber,
		arg.Amount,
		arg.IdempotencyKey,
		arg.PaidAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.WeekNumber,
		&i.Amount,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByLoanID = `-- name: ListPaymentsByLoanID :many
SELECT id,
  loan_id,
  week_number,
  amount,
  paid_at
FROM payments
WHERE loan_id = $1::bigint
  AND (
    (
      $2::timestamptz IS NULL
      AND $3::bigint IS NULL
    )
    OR (
      (paid_at, id) > (
        $2::timestamptz,
        $3::bigint
      )
    )
  )
ORDER BY paid_at ASC,
  id ASC
LIMIT $4::int
`

type ListPaymentsByLoanIDParams struct {
	LoanID       int64
	CursorPaidAt pgtype.Timestamptz
	CursorID     pgtype.Int8
	LimitVal     int32
}

type ListPaymentsByLoanIDRow struct {
	ID         int64
	LoanID     int64
	WeekNumber int32
	Amount     int64
	PaidAt     pgtype.Timestamp
}

func (q *Queries) ListPaymentsByLoanID(ctx context.Context, arg ListPaymentsByLoanIDParams) ([]ListPaymentsByLoanIDRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByLoanID,
		arg.LoanID,
		arg.CursorPaidAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsByLoanIDRow
	for rows.Next() {
		var i ListPaymentsByLoanIDRow
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.WeekNumber,
			&i.Amount,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
